export const chainListData = [
  {
    id: 'ethereum',
    chain_type: 'evm',
    chain_supported: true,
    chain_airdrop: false,
    chain_name: 'Ethereum',
    chain_symbol: 'ETH',
    chain_logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
    chain_coin: {
      name: 'Etherem',
      symbol: 'ETH',
      decimals: 18,
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
      wrapped_address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    },
    mainnet_configuration: {
      name: 'Ethereum',
      rpc: 'https://eth.llamarpc.com\t',
      id: 1,
      hex: '0x1',
      symbol: 'ETH',
      explorer: 'https://etherscan.io',
    },
    testnet_configuration: [
      {
        name: 'Ethereum Goerli',
        rpc: 'https://rpc.ankr.com/eth_goerli',
        id: 5,
        hex: '0x5',
        symbol: 'ETH',
        explorer: 'https://goerli.etherscan.io',
      },
      {
        name: 'Ethereum Sepolia',
        rpc: 'https://endpoints.omniatech.io/v1/eth/sepolia/public',
        id: 11155111,
        hex: '0xaa36a7',
        symbol: 'ETH',
        explorer: 'https://sepolia.etherscan.io',
      },
    ],
    explorers: {
      mainnet: {
        name: 'Etherscan',
        url: 'https://etherscan.io/',
        logo: 'https://etherscan.io/images/favicon3.ico',
        api_url: 'https://api.etherscan.io',
        api_key: process.env.NEXT_PUBLIC_ETHERSCAN_KEY,
      },
      goerli: {
        name: 'Etherscan',
        url: 'https://goerli.etherscan.io/',
        logo: 'https://etherscan.io/images/favicon3.ico',
        api_url: 'https://api-goerli.etherscan.io',
        api_key: process.env.NEXT_PUBLIC_ETHERSCAN_KEY,
      },
      sepolia: {
        name: 'Etherscan',
        url: 'https://sepolia.etherscan.io/',
        logo: 'https://etherscan.io/images/favicon3.ico',
        api_url: 'https://api-sepolia.etherscan.io',
        api_key: process.env.NEXT_PUBLIC_ETHERSCAN_KEY,
      },
    },
    platforms: {
      coingeckoId: 'ethereum',
      moralisId: 'eth',
    },
  },
  {
    id: 'bnbchain',
    chain_type: 'evm',
    chain_supported: true,
    chain_airdrop: false,
    chain_name: 'BNB Chain',
    chain_symbol: 'BNB',
    chain_logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png',
    chain_coin: {
      name: 'BNB',
      symbol: 'BNB',
      decimals: 18,
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png',
      wrapped_address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
    },
    mainnet_configuration: {
      name: 'BNB Chain',
      rpc: 'https://bsc-dataseed1.binance.org/',
      id: 56,
      hex: '0x38',
      symbol: 'BNB',
      explorer: 'https://bscscan.com',
    },
    testnet_configuration: [
      {
        name: 'BNB Chain Testnet',
        rpc: 'https://data-seed-prebsc-1-s3.binance.org:8545/',
        id: 97,
        hex: '0x61',
        symbol: 'tBNB',
        explorer: 'https://testnet.bscscan.com/',
      },
      {
        name: 'opBNB Testnet',
        rpc: 'https://opbnb-testnet-rpc.bnbchain.org',
        id: 5611,
        hex: '0x15eb',
        symbol: 'tBNB',
        explorer: 'https://opbnb-testnet.bscscan.com',
      },
    ],
    explorers: {
      mainnet: {
        name: 'BscScan',
        url: 'https://bscscan.com',
        logo: 'https://bscscan.com/images/favicon.ico',
        api_url: 'https://api.bscscan.com',
        api_key: process.env.NEXT_PUBLIC_BSCSCAN_KEY,
      },
      testnet: {
        name: 'BscScan',
        url: 'https://testnet.bscscan.com',
        logo: 'https://bscscan.com/images/favicon.ico',
        api_url: 'https://api-testnet.bscscan.com',
        api_key: process.env.NEXT_PUBLIC_BSCSCAN_KEY,
      },
    },
    platforms: {
      coingeckoId: 'binancecoin',
      moralisId: 'bsc',
    },
  },
  {
    id: 'avalanche',
    chain_type: 'evm',
    chain_supported: true,
    chain_airdrop: false,
    chain_name: 'Avalanche',
    chain_symbol: 'AVAX',
    chain_logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png',
    chain_coin: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18,
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png',
      wrapped_address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
    },
    mainnet_configuration: {
      name: 'Avalanche',
      rpc: 'https://api.avax.network/ext/bc/C/rpc',
      id: 43114,
      hex: '0xa86a',
      symbol: 'AVAX',
      explorer: 'https://snowtrace.io',
    },
    testnet_configuration: [
      {
        name: 'Avalanche Fuji',
        rpc: 'https://api.avax-test.network/ext/bc/C/rpc',
        id: 43113,
        hex: '0xa869',
        symbol: 'AVAX',
        explorer: 'https://testnet.snowtrace.io',
      },
    ],
    explorers: {
      mainnet: {
        name: 'SnowTrace',
        url: 'https://snowtrace.io/',
        logo: 'https://snowtrace.io/images/favicon.ico',
        api_url: 'https://api.snowtrace.io',
        api_key: process.env.NEXT_PUBLIC_SNOWTRACE_KEY,
      },
      testnet: {
        name: 'SnowTrace',
        url: 'https://testnet.snowtrace.io/',
        logo: 'https://snowtrace.io/images/favicon.ico',
        api_url: 'https://api-testnet.snowtrace.io',
        api_key: process.env.NEXT_PUBLIC_SNOWTRACE_KEY,
      },
    },
    platforms: {
      coingeckoId: 'avalanche-2',
      moralisId: 'avalanche',
    },
  },
  {
    id: 'matic-network',
    chain_type: 'evm',
    chain_supported: true,
    chain_airdrop: false,
    chain_name: 'Polygon',
    chain_symbol: 'MATIC',
    chain_logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png',
    chain_coin: {
      name: 'Polygon',
      symbol: 'MATIC',
      decimals: 18,
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png',
      wrapped_address: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270',
    },
    mainnet_configuration: {
      name: 'Polygon ',
      rpc: 'https://polygon-rpc.com/',
      id: 137,
      hex: '0x89',
      symbol: 'AVAX',
      explorer: 'https://polygonscan.com',
    },
    testnet_configuration: [
      {
        name: 'Polygon Testnet',
        rpc: 'https://matic-mumbai.chainstacklabs.com',
        id: 80001,
        hex: '0x13881',
        symbol: 'MATIC',
        explorer: 'https://mumbai.polygonscan.com/',
      },
    ],
    explorers: {
      mainnet: {
        name: 'PolygonScan',
        url: 'https://polygonscan.com/',
        logo: 'https://polygonscan.com/images/favicon.ico',
        api_url: 'https://api.polygonscan.com',
        api_key: process.env.NEXT_PUBLIC_POLYGON_KEY,
      },
      testnet: {
        name: 'PolygonScan',
        url: 'https://mumbai.polygonscan.com',
        logo: 'https://polygonscan.com/images/favicon.ico',
        api_url: 'https://api-testnet.polygonscan.com',
        api_key: process.env.NEXT_PUBLIC_POLYGON_KEY,
      },
    },
    platforms: {
      coingeckoId: 'matic-network',
      moralisId: 'polygon',
    },
  },
  {
    id: 'fantom',
    chain_type: 'evm',
    chain_supported: true,
    chain_airdrop: false,
    chain_name: 'Fantom',
    chain_symbol: 'FTM',
    chain_logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3513.png',
    chain_coin: {
      name: 'Fantom',
      symbol: 'FTM',
      decimals: 18,
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3513.png',
      wrapped_address: '0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83',
    },
    mainnet_configuration: {
      name: 'Fantom Opera',
      rpc: 'https://rpcapi.fantom.network',
      id: 250,
      hex: '0xfa',
      symbol: 'FTM',
      explorer: 'https://ftmscan.com',
    },
    testnet_configuration: [
      {
        name: 'Fantom Testnet',
        rpc: 'https://rpc.testnet.fantom.network/',
        id: 4002,
        hex: '0xfa2',
        symbol: 'FTM',
        explorer: 'https://testnet.ftmscan.com/',
      },
    ],
    explorers: {
      mainnet: {
        name: 'FtmScan',
        url: 'https://ftmscan.com',
        logo: 'https://ftmscan.com/images/favicon.png',
        api_url: 'https://api.ftmscan.com',
        api_key: process.env.NEXT_PUBLIC_FTMSCAN_KEY,
      },
      testnet: {
        name: 'PolygonScan',
        url: 'https://testnet.ftmscan.com/',
        logo: 'https://ftmscan.com/images/favicon.png',
        api_url: 'https://api-testnet.ftmscan.com',
        api_key: process.env.NEXT_PUBLIC_FTMSCAN_KEY,
      },
    },
    platforms: {
      coingeckoId: 'fantom',
      moralisId: 'fantom',
    },
  },
  {
    id: 'crypto-com-chain',
    chain_type: 'evm',
    chain_supported: true,
    chain_airdrop: false,
    chain_name: 'Cronos',
    chain_symbol: 'CRO',
    chain_logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png',
    chain_coin: {
      name: 'Cronos',
      symbol: 'CRO',
      decimals: 18,
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png',
      wrapped_address: '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23',
    },
    mainnet_configuration: {
      name: 'Cronos',
      rpc: 'https://evm.cronos.org',
      id: 25,
      hex: '0x19',
      symbol: 'FTM',
      explorer: 'https://cronoscan.com',
    },
    testnet_configuration: [
      {
        name: 'Cronos testnet',
        rpc: 'https://evm-t3.cronos.org',
        id: 338,
        hex: '0x152',
        symbol: 'tCRO',
        explorer: 'https://cronos.org/explorer/testnet3/',
      },
    ],
    explorers: {
      mainnet: {
        name: 'CronoScan',
        url: 'https://cronoscan.com',
        logo: 'https://cronoscan.com/images/favicon.png',
        api_url: 'https://api.cronoscan.com',
        api_key: process.env.NEXT_PUBLIC_CRONOSCAN_KEY,
      },
    },
    platforms: {
      coingeckoId: 'crypto-com-chain',
      moralisId: 'cronos',
    },
  },
  {
    id: 'arbitrum',
    chain_type: 'evm',
    chain_supported: true,
    chain_airdrop: false,
    chain_name: 'Arbitrum',
    chain_symbol: 'ARB',
    chain_logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11841.png',
    chain_coin: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
      logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/11841.png',
      wrapped_address: '0x912CE59144191C1204E64559FE8253a0e49E6548',
      address: '0x912CE59144191C1204E64559FE8253a0e49E6548',
    },
    mainnet_configuration: {
      name: 'Arbitrum One',
      rpc: 'https://arb1.arbitrum.io/rpc',
      id: 42161,
      hex: '0xa4b1',
      symbol: 'ETH',
      explorer: 'https://arbiscan.io',
    },
    testnet_configuration: [
      {
        name: 'Arbitrum Goerli',
        rpc: 'https://goerli-rollup.arbitrum.io/rpc',
        id: 421613,
        hex: '0x66eed',
        symbol: 'ETH',
        explorer: 'https://goerli.arbiscan.io/',
      },
    ],
    explorers: {
      mainnet: {
        name: 'ArbiScan',
        url: 'https://arbiscan.io',
        logo: 'https://arbiscan.io/images/favicon.ico',
        api_url: 'https://api.arbiscan.io',
        api_key: process.env.NEXT_PUBLIC_ARBITRUM_KEY,
      },
      testnet: {
        name: 'ArbiScan',
        url: 'https://goerli.arbiscan.io/',
        logo: 'https://arbiscan.io/images/favicon.ico',
        api_url: 'https://api-goerli.arbiscan.io',
        api_key: process.env.NEXT_PUBLIC_ARBITRUM_KEY,
      },
    },
    platforms: {
      coingeckoId: 'ethereum',
      moralisId: 'arbitrum',
    },
  },
  {
    id: 'linea',
    chain_type: 'evm',
    chain_supported: false,
    chain_airdrop: true,
    chain_name: 'Linea',
    chain_symbol: 'LINEA',
    chain_logo: 'https://raw.githubusercontent.com/MetaMask/metamask-extension/develop/app/images/linea-logo-mainnet.png',
    chain_coin: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
      logo: 'https://raw.githubusercontent.com/MetaMask/metamask-extension/develop/app/images/linea-logo-mainnet.png',
      wrapped_address: '0x912CE59144191C1204E64559FE8253a0e49E6548',
    },
    mainnet_configuration: {
      name: 'Linea',
      rpc: 'https://linea-mainnet.infura.io/v3/',
      id: 59144,
      hex: '0xe708',
      symbol: 'ETH',
      explorer: 'https://lineascan.build/',
    },
    testnet_configuration: [
      {
        name: 'Linea Testnet',
        rpc: 'https://linea-goerli.infura.io',
        id: 59140,
        hex: '0xe704',
        symbol: 'ETH',
        explorer: 'https://explorer.goerli.linea.build',
      },
    ],
    explorers: {
      mainnet: {
        name: 'LineaScan',
        url: 'https://lineascan.build',
        logo: 'https://lineascan.build/images/favicon.ico',
        api_url: 'https://api.lineascan.build',
        api_key: null,
      },
      testnet: {
        name: 'LineaScan',
        url: 'https://goerli.lineascan.build/',
        logo: 'https://goerli.lineascan.build/images/favicon.ico',
        api_url: 'https://api-testnet.lineascan.build',
        api_key: null,
      },
    },
    platforms: {
      coingeckoId: null,
      moralisId: null,
    },
  },
  {
    id: 'base',
    chain_type: 'evm',
    chain_supported: false,
    chain_airdrop: true,
    chain_name: 'Base',
    chain_symbol: 'BASE',
    chain_logo: 'https://avatars.githubusercontent.com/u/108554348?s=200&v=4',
    chain_coin: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
      logo: 'https://avatars.githubusercontent.com/u/108554348?s=200&v=4',
      wrapped_address: null,
    },
    mainnet_configuration: {
      name: 'Base',
      rpc: 'https://developer-access-mainnet.base.org',
      id: 8453,
      hex: '0x2105',
      symbol: 'ETH',
      explorer: 'https://basescan.org',
    },
    testnet_configuration: [
      {
        name: 'Base Goerli',
        rpc: 'https://goerli.base.org',
        id: 84531,
        hex: '0x14a33',
        symbol: 'ETH',
        explorer: 'https://goerli.basescan.org',
      },
    ],
    explorers: {
      mainnet: {
        name: 'BaseScan',
        url: 'https://basescan.org',
        logo: 'https://basescan.org/images/favicon.ico',
        api_url: 'https://api.basescan.org/',
        api_key: null,
      },
      testnet: {
        name: 'BaseScan',
        url: 'https://goerli.basescan.org',
        logo: 'https://goerli.basescan.org/images/favicon.ico',
        api_url: 'https://api-goerli.basescan.org',
        api_key: null,
      },
    },
    platforms: {
      coingeckoId: null,
      moralisId: null,
    },
  },
]
